owner: blakeoppenheim # Your GitHub username
repo: nvgtr-status # Your repository name

sites:
  - name: NVGTR AI
    url: https://app.nvgtr.ai
  - name: NVGTR API
    url: https://app.nvgtr.ai/api/health
  - name: NVGTR Website
    url: https://nvgtr.ai

status-website:
  cname: status.nvgtr.ai
  name: NVGTR Status
  introTitle: "NVGTR System Status"
  introMessage: "This page provides real-time status information for NVGTR services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: NVGTR
      href: https://nvgtr.ai

# Notifications
notifications:
  email:
    - support@nvgtr.ai # Replace with your email

# Upptime also supports notifications on Slack, Discord, and Telegram
# For more information, see https://upptime.js.org/docs/notifications

i18n:
  footer: NVGTR System Status